name: check

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'tools/**'
      - '**/*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'tools/**'
      - '**/*.md'

jobs:
  spotless-check:
    name: 'Linux Spotless Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          job-id: jdk${{ matrix.jdk }}
          remote-build-cache-proxy-enabled: false
          arguments: spotlessCheck