name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'tools/**'
      - '**/*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'tools/**'
      - '**/*.md'

# cancel repeated workflow
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-jdk17-build: # LTS JDK version, don't remove until EOL
    name: 'Linux JDK 17 Gradle Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: burrunan/gradle-cache-action@v1
        name: Test
        with:
          job-id: jdk${{ matrix.jdk }}
          remote-build-cache-proxy-enabled: false
          arguments: build -x test --scan